---
collections:
  # Install a collection from Ansible Galaxy.
  - name: amazon.aws
    version: "5.5.1"

  - name: community.docker
    version: "3.7.0"

  - name: community.aws
    version: "7.2.0"
