- name: Configure python virtualenv and install services
  hosts: "{{ var_hosts | default('webheads') }}"
  vars_files:
  - ../vars/conf.yml

  tasks:
    - name: delete live directory
      file:
        path: "{{ live_doc_root }}htaccess"
        state: absent

    - name: checkout the live redirects
      git:
        repo: "https://github.com/thunderbird/live-redirects.git"
        dest: "{{ live_doc_root }}"
        version: "{{ branch | default('prod') }}"
        force: True

    - name: write commit hash to version.txt
      shell: 'cd "{{ live_doc_root }}htaccess" && git rev-parse HEAD > version.txt'