- name: Install style.thunderbird.net files
  hosts: "{{ var_hosts | default('webheads') }}"
  vars_files:
  - ../vars/conf.yml

  tasks:
  - name: checkout style-guide repo
    git:
      repo: "https://github.com/thunderbird/style-guide.git"
      dest: "{{ style_files }}"
      version: "{{ branch | default('prod') }}"
