region: us-west-2
key_pair: tb-amo-ops-key
vpc_id: vpc-441e5e22
subnet_id: subnet-35f0477d
ami: 'ami-08c191625cfb7ee61'
settings_file: '../settings_local.py'

# versioncheck servers
sec_group_names: ["amo-versioncheck-prod-tb", "add-ssh"]
target_group: 'amo-prod-versioncheck'
instance_type: 'c7a.medium'
node_count: '2'
volume_size: '100'
count_tag:
  uwsgi: 'versioncheck'
filter_tag:
  'tag:uwsgi': 'versioncheck'
  'instance-state-name': 'running'
ini_file: '../versioncheck.ini'
docker_volumes:
  - /data/olympia/settings_local.py:/data/olympia/settings_local.py:Z
  - /data/olympia/versioncheck.ini:/etc/uwsgi.d/versioncheck.ini:Z
docker_command: /bin/bash -c "/usr/sbin/uwsgi --uid root --gid root /etc/uwsgi.d/versioncheck.ini"
